name: NER
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Minimum supported version; use 3.10 or 3.11 if preferred
  - python-dotenv
  - pydantic
  - pydantic-settings
  - typer
  - numpy
  - pandas
  - pip
  - pip:
    - torch
    - transformers
    - pytest
    - rapidfuzz
